# Generated by Django 6.0.2 on 2026-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='intervals',
            field=models.TextField(default='{"1": 20, "2": 30, "3": 60, "4": 120, "5": 240}'),
        ),
    ]
