# Generated by Django 6.0.2 on 2026-02-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usersettings_intervals'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
