# Generated by Django 6.0.2 on 2026-02-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_callrecord_notified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='sound_name',
        ),
    ]
