# Generated by Django 6.0.2 on 2026-02-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usersettings_sound_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='first_work_day',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='first_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='Первый рабочий день'),
        ),
    ]
