# Generated by Django 6.0.2 on 2026-02-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usersettings_first_work_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='dark_theme',
            field=models.BooleanField(default=False, verbose_name='Тёмная тема'),
        ),
    ]
