# Generated by Django 6.0.2 on 2026-02-13 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersettings_dark_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Справочная тема',
                'verbose_name_plural': 'Справочные темы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HelpTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вкладки')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='core.helptopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Вкладка справочника',
                'verbose_name_plural': 'Вкладки справочника',
                'ordering': ['order', 'title'],
            },
        ),
    ]
