# Generated by Django 6.0.2 on 2026-02-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_helptopic_helptab'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingrecord',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
        migrations.AddField(
            model_name='trackingrecord',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='call_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.callrecord', verbose_name='Связанный звонок'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='claim',
            field=models.CharField(max_length=255, verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='connection_datetime',
            field=models.DateTimeField(verbose_name='Дата/время подключения'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='crm',
            field=models.CharField(max_length=100, verbose_name='Номер СРМ'),
        ),
        migrations.AlterField(
            model_name='trackingrecord',
            name='status',
            field=models.CharField(default='Активна', max_length=50, verbose_name='Статус'),
        ),
    ]
